apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valdrics.fullname" . }}-grafana-datasources
  labels:
    {{- include "valdrics.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.monitoring.prometheus.url | default "http://prometheus:9090" | quote }}
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          httpMethod: POST

      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: {{ .Values.monitoring.alertmanager.url | default "http://alertmanager:9093" | quote }}
        editable: false
        jsonData:
          implementation: prometheus
